name: Manual Tag Release

on:
  workflow_dispatch:
  push:

jobs:
  increment_version:
    runs-on: ubuntu-latest
    steps:
      - name: Increment version
        # run: |
        #   echo '1' > version.txt
        #   current=$(cat version.txt)
        #   echo $((current + 1)) > version.txt
        #   echo "NEW_VERSION=$(cat version.txt)" >> $GITHUB_ENV
        #   echo "$env.NEW_VERSION"
        #   cat version.txt
        run: |
          echo 'v1.2.3' > version.txt
          version=$(cat version.txt)

          # Разбиваем на компоненты
          IFS='.' read -ra parts <<< "${version#v}"
          major=${parts[0]}
          minor=${parts[1]}
          patch=${parts[2]}

          # Увеличиваем PATCH на 1
          patch=$((patch + 1))

          # Собираем новую версию
          new_version="v${major}.${minor}.${patch}"

          # Записываем обратно
          echo "$new_version" > version.txt

          echo "Updated version: $new_version"
                    
