name: Release
on:
  push:
    tags:
      - 'v*'  # Запускать при пуше тегов вида v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Build and publish
        run: |
          echo "Building version $VERSION"
          # Здесь может быть сборка пакета (npm, pip, docker и т. д.)
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.VERSION }}
          body: "See CHANGELOG.md for details"
