name: Manual Tag Release

on:
  workflow_dispatch:
  push:

jobs:
  increment_version:
    runs-on: ubuntu-latest
    steps:
      - name: Increment version
        run: |
          echo '1' > version.txt
          current=$(cat version.txt)
          echo $((current + 1)) > version.txt
          echo "NEW_VERSION=$(cat version.txt)" >> $GITHUB_ENV
          
